### ISSUE TITLE
Create team, do a test run

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/labelfree-cellpainting#3]
Let's use this thread for getting Pratik (@duttaprat) started.
Shantanu: @shntnu 
Csaba: @csmolnar 
Juan: @jccaicedo 
Greg: @gwaygenomics

**Comment by duttaprat** [comment]
@shntnu Should I upload the modified repository here?
It seems I can not upload the code.

**Comment by shntnu** [comment]
@duttaprat I have given you access now. Yes, please use this repo for your code, including notebooks. You will need to do so via pull request.

**Comment by gwaygenomics** [comment]
@duttaprat 

> Should I upload the modified repository here?

Let's not add the full repo here. What does the LICENSE say in the repo?

**Comment by gwaygenomics** [comment]
Here is their [LICENSE](https://github.com/AllenCellModeling/pytorch_fnet/blob/master/LICENSE). It is 2-clause BSD for academic use. 

It also looks like the Allen Institute folks welcome contributions to their source code ([CONTRIBUTING.md](https://github.com/AllenCellModeling/pytorch_fnet/blob/master/CONTRIBUTING.md)).

We should use the standard open source workflows that they recommend in the CONTRIBUTING document. Concretely, this means forking their repo to your github user and using any modifications you made to your fork here. We can then think about pushing some of the modifications on your fork back to the upstream (original) `pytorch_fnet` repo, but this is not necessary.

**Comment by shntnu** [comment]
Ohh – good point @gwaygenomics! I interpreted Pratik's question to be whether he can use this repo for his project's notebooks. But are you suggesting taking the approach you've outlined above even for that?

**Comment by gwaygenomics** [comment]
There are two things working here:

1. pytorch_fnet code - @duttaprat needed to modify this in some way to get working for our data, correct?
2. implementation (training, testing, evaluating)

I am saying that 1 should live in a fork of the pytorch_net upstream (can be owned by @shntnu or @duttaprat , but @duttaprat should be a maintainer). 2 is this repo. [Optional] We can use a submodule to connect 2 to the fork of 1

**Comment by gwaygenomics** [comment]
it's possible I have the vision backwards and this is already thought through! Please do ignore if so

**Comment by shntnu** [comment]
Thanks @gwaygenomics! I've thought through very little on how to set this up, and your continued guidance on this will be fantastic.

1. https://github.com/broadinstitute/pytorch_fnet is the fork that @duttaprat should use to make modifications that are needed (he has maintainer rights, so does @broadinstitute/label-free-imaging). I don't think he needs to make any changes to the codebase though, but it's wise to create a fork so he can do so if needed

2. the starting point for this should probably be the code in this example directory https://github.com/broadinstitute/pytorch_fnet/tree/master/examples. So concretely, @duttaprat would copy that code to this repo (including the licence https://github.com/AllenCellModeling/pytorch_fnet/blob/master/LICENSE) and then modify as needed

The submodule idea is the right way to do it to ensure reproducibility and a tight link to the code used to produce the results. But it might complicate things if @duttaprat is not already familiar with working with submodules.

**Comment by duttaprat** [comment]
Thanks @shntnu and @gwaygenomics for the discussion. 

@shntnu I will fork from https://github.com/broadinstitute/pytorch_fnet  and do the needed modification.

**Comment by duttaprat** [comment]
Hi @shntnu @gwaygenomics and @csmolnar, I have successfully run the code. The code now predicted the brightfield images. The predicted folder contains the predicted images and their labels. Due to its size, I can not upload it in GitHuib, rather I have uploaded my Google drive and the link is 
https://drive.google.com/drive/folders/1vpt3IszH0SCMJSZgd3pR69yMsjkfTyGF?usp=sharing

Please check the link. I will upload the modified files via push request by tonight.  Also, as per the previous meeting, I think we should run the code on your dataset. Please provide me that dataset. Also, if you have any suggestions, please let me know.

**Comment by duttaprat** [comment]
Hello all, I have modified the code in my repo and made a push request into https://github.com/broadinstitute/pytorch_fnet. 
 
Please check if the code is working in your system/AWS.

**Comment by shntnu** [comment]
@duttaprat Congratulations on getting this to run!

I don't see your pull request in  https://github.com/broadinstitute/pytorch_fnet

We will address access to the pilot data in #5 and then discuss the next steps once you've confirmed that works.

Regarding your current results – can you briefly summarize what you've achieved?

**Comment by duttaprat** [comment]
Thanks @shntnu. Regarding the summarization, what should I report? How to run the code or what insights I draw from the prediction?

**Comment by duttaprat** [comment]
@shntnu can you again check if there is any pull request?

**Comment by shntnu** [comment]
> Thanks @shntnu. Regarding the summarization, what should I report? How to run the code or what insights I draw from the prediction?

This is what I see in your `predictions.csv`. Can you explain what is each row? How long did it take to run each? How big is each image (input as well as output) in terms of number of pixels?

|channel_signal |channel_target | fnet.metrics.corr_coef.|path_prediction_c0.       |path_signal       |path_target       |path_tiff                                                                                                 |
|:--------------|:--------------|-----------------------:|:-------------------------|:-----------------|:-----------------|:---------------------------------------------------------------------------------------------------------|
|[3]            |[2]            |                   0.204|tifs/0_prediction_c0..tif |tifs/0_signal.tif |tifs/0_target.tif |fovs/6c610aeb_3500000635_100X_20170227_E08_P20.ome.tiff |
|[3]            |[2]            |                   0.261|tifs/1_prediction_c0..tif |tifs/1_signal.tif |tifs/1_target.tif |fovs/dd9a36d6_3500000635_100X_20170227_F07_P25.ome.tiff |
|[3]            |[2]            |                   0.163|tifs/2_prediction_c0..tif |tifs/2_signal.tif |tifs/2_target.tif |fovs/52ae096a_3500000635_100X_20170227_E08_P09.ome.tiff |
|[3]            |[2]            |                   0.156|tifs/3_prediction_c0..tif |tifs/3_signal.tif |tifs/3_target.tif |fovs/3b66c61f_3500000635_100X_20170227_E08_P13.ome.tiff |
|[3]            |[2]            |                   0.138|tifs/4_prediction_c0..tif |tifs/4_signal.tif |tifs/4_target.tif |fovs/c0bc63c3_3500000635_100X_20170227_E07_P05.ome.tiff |
|[3]            |[2]            |                   0.258|tifs/5_prediction_c0..tif |tifs/5_signal.tif |tifs/5_target.tif |fovs/0be0e248_3500000635_100X_20170227_E08_P10.ome.tiff |
|[3]            |[2]            |                   0.403|tifs/6_prediction_c0..tif |tifs/6_signal.tif |tifs/6_target.tif |fovs/a857723d_3500000635_100X_20170227_E08_P18.ome.tiff |
|[3]            |[2]            |                   0.212|tifs/7_prediction_c0..tif |tifs/7_signal.tif |tifs/7_target.tif |fovs/2155a4fe_3500000635_100X_20170227_E08_P21.ome.tiff |
|[3]            |[2]            |                   0.342|tifs/8_prediction_c0..tif |tifs/8_signal.tif |tifs/8_target.tif |fovs/83be6849_3500000635_100X_20170227_E07_P08.ome.tiff |
|[3]            |[2]            |                   0.215|tifs/9_prediction_c0..tif |tifs/9_signal.tif |tifs/9_target.tif |fovs/37c1b049_3500000635_100X_20170227_F07_P27.ome.tiff |

This is your `predict_options.json` file. Were these default params?  Was there any other files where you needed to set params?

```json
{
    "dataset": "fnet.data.MultiChTiffDataset",
    "dataset_kwargs": {
        "path_csv": "/home1/pratik/CellPainting/pytorch_fnet/examples/image_list_test.csv"
    },
    "gpu_ids": 0,
    "idx_sel": null,
    "metric": "fnet.metrics.corr_coef",
    "n_images": -1,
    "no_prediction": false,
    "no_signal": false,
    "no_target": false,
    "path_model_dir": [
        "/home1/pratik/CellPainting/pytorch_fnet/examples/model/"
    ],
    "path_save_dir": "predictions",
    "path_tif": null
}
```

**Comment by shntnu** [comment]
> @shntnu can you again check if there is any pull request?

I see it now
https://github.com/broadinstitute/pytorch_fnet/pull/1/files

**Comment by duttaprat** [comment]
> > Thanks @shntnu. Regarding the summarization, what should I report? How to run the code or what insights I draw from the prediction?
> 
> This is what I see in your `predictions.csv`. Can you explain what is each row? How long did it take to run each? How big is each image (input as well as output) in terms of number of pixels?
> 
> channel_signal	channel_target	fnet.metrics.corr_coef.	path_prediction_c0.	path_signal	path_target	path_tiff
> [3]	[2]	0.204	tifs/0_prediction_c0..tif	tifs/0_signal.tif	tifs/0_target.tif	fovs/6c610aeb_3500000635_100X_20170227_E08_P20.ome.tiff
> [3]	[2]	0.261	tifs/1_prediction_c0..tif	tifs/1_signal.tif	tifs/1_target.tif	fovs/dd9a36d6_3500000635_100X_20170227_F07_P25.ome.tiff
> [3]	[2]	0.163	tifs/2_prediction_c0..tif	tifs/2_signal.tif	tifs/2_target.tif	fovs/52ae096a_3500000635_100X_20170227_E08_P09.ome.tiff
> [3]	[2]	0.156	tifs/3_prediction_c0..tif	tifs/3_signal.tif	tifs/3_target.tif	fovs/3b66c61f_3500000635_100X_20170227_E08_P13.ome.tiff
> [3]	[2]	0.138	tifs/4_prediction_c0..tif	tifs/4_signal.tif	tifs/4_target.tif	fovs/c0bc63c3_3500000635_100X_20170227_E07_P05.ome.tiff
> [3]	[2]	0.258	tifs/5_prediction_c0..tif	tifs/5_signal.tif	tifs/5_target.tif	fovs/0be0e248_3500000635_100X_20170227_E08_P10.ome.tiff
> [3]	[2]	0.403	tifs/6_prediction_c0..tif	tifs/6_signal.tif	tifs/6_target.tif	fovs/a857723d_3500000635_100X_20170227_E08_P18.ome.tiff
> [3]	[2]	0.212	tifs/7_prediction_c0..tif	tifs/7_signal.tif	tifs/7_target.tif	fovs/2155a4fe_3500000635_100X_20170227_E08_P21.ome.tiff
> [3]	[2]	0.342	tifs/8_prediction_c0..tif	tifs/8_signal.tif	tifs/8_target.tif	fovs/83be6849_3500000635_100X_20170227_E07_P08.ome.tiff
> [3]	[2]	0.215	tifs/9_prediction_c0..tif	tifs/9_signal.tif	tifs/9_target.tif	fovs/37c1b049_3500000635_100X_20170227_F07_P27.ome.tiff
> This is your `predict_options.json` file. Were these default params? Was there any other files where you needed to set params?
> 
> ```json
> {
>     "dataset": "fnet.data.MultiChTiffDataset",
>     "dataset_kwargs": {
>         "path_csv": "/home1/pratik/CellPainting/pytorch_fnet/examples/image_list_test.csv"
>     },
>     "gpu_ids": 0,
>     "idx_sel": null,
>     "metric": "fnet.metrics.corr_coef",
>     "n_images": -1,
>     "no_prediction": false,
>     "no_signal": false,
>     "no_target": false,
>     "path_model_dir": [
>         "/home1/pratik/CellPainting/pytorch_fnet/examples/model/"
>     ],
>     "path_save_dir": "predictions",
>     "path_tif": null
> }
> ```

Sure I will do that thing and share it with you.

**Comment by duttaprat** [comment]
> 
> This is your `predict_options.json` file. Were these default params? Was there any other files where you needed to set params?
> 


These were the default params.

**Comment by duttaprat** [comment]
> 
> This is what I see in your `predictions.csv`. Can you explain what is each row? How long did it take to run each? How big is each image (input as well as output) in terms of number of pixels?
> 

I have created a [readme](https://docs.google.com/document/d/1kjY8lpdHq2a_JWpgiGFOf0D7m8hVgv8u3S7Vy69vOjY/edit?usp=sharing) file here.

**Comment by shntnu** [comment]
Thanks for explaining the output @duttaprat. We have enough to get started on testing it on the pilot dataset. I'll create a new issue.
