### ISSUE TITLE
Confirm access to pilot dataset

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/labelfree-cellpainting#5]
@duttaprat Let me know if you're able to download this dataset.

First, install `awscli` using `pip install awscli`.

Then, download using this command (I will send you `SECRET_FOLDER_LOCATION` by email because we haven't yet set up a requestor pays model and want to avoid random bulk downloads)

```sh
aws s3 sync \
  --no-sign-request \
  --region us-east-1 \
  ${FOLDER_LOCATION}  .
```

**Comment by shntnu** [comment]
@duttaprat The dataset is 56.6 GB, so you'd definitely want to do it on your server

**Comment by duttaprat** [comment]
Okay.

**Comment by shntnu** [comment]
Great. Here's a description of the dataset https://github.com/broadinstitute/labelfree-cellpainting/tree/stain3/datasets/Stain3_Standard_BR00115134 (in #6)

**Comment by duttaprat** [comment]
Okay...I will go through the description.

**Comment by duttaprat** [comment]
@shntnu Thanks for updating the [project description doc](https://docs.google.com/document/d/1ZyQDczsbc-DonxjWNo-iAAm9kEFpi7IR9RuBkGIqa9g/edit). 

I am working on the pilot data and writing code for it. Will update as soon as I get some results on it.

**Comment by shntnu** [comment]
@duttaprat Please go ahead and approve #6 (see [docs](https://help.github.jp/enterprise/2.11/user/articles/approving-a-pull-request-with-required-reviews/) if you have not done this before) and I can then merge it into main
